### ISSUE TITLE
Calling to_json on FeatureFlagsState instance throws error in Ruby 2.5.6

### ISSUE THREAD

**Issue by binan-trc** [launchdarkly/ruby-server-sdk#164]
**Describe the bug**
In our Ruby 2.5.6 app, calling `to_json` on a `FeatureFlagsState` instance throws error.

**To reproduce**
Initialize a `LDClient` instance.
Call `all_flags_state` to get the `FeatureFlagsState` instance.
Call `to_json` on the `FeatureFlagsState` instance to get the error.

(If I call `as_json.to_json` instead of just `to_json`, it works)

**Expected behavior**
It should return the corresponding JSON string. 

**Logs**
Traceback (most recent call last):
NoMethodError (undefined method `merge' for []:Array)

**SDK version**
5.8.0

**Language version, developer tools**
Ruby 2.5.6

**OS/platform**
Ubuntu 14.04

**Additional context**
The same statement works fine in our Ruby 2.4.5 app.

**Comment by eli-darkly** [comment]
I'm unable to reproduce this... and I would've been very surprised if I _could_ reproduce it, since 1. `to_json` is literally defined as `as_json.to_json`, so I don't see how they could behave so differently, and 2. both `as_json` and `to_json` are covered in the unit tests. I did consider whether there could be something specific to Ruby 2.5.6 that would cause this, since the CI tests had been running in 2.5.3, but using 2.5.6 didn't make any difference; it still works fine for me.

The SDK's implementation of these methods is very simple and does not have any references to `Array.merge`. It'd be helpful if you could provide the actual call stack of the error— what you posted here under "Traceback" isn't a traceback, it's just a plain error message with no code locations.

**Comment by binan-trc** [comment]
Sorry I made the assumption the problem was with a specific the Ruby version. We are running Rails. The backtrace of the exception actually gave nil which is weird. 

So I created a brand new app with latest Rails 6.0.3.3, and ran `LaunchDarkly::LDClient.new(sdk_key).all_flags_state(key:1).to_json` and got a different error: 

*** TypeError Exception: no implicit conversion of Symbol into Integer

Backtrace: 
["/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/core_ext/object/json.rb:161:in `as_json'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/json/encoding.rb:35:in `encode'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/json/encoding.rb:22:in `encode'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/core_ext/object/json.rb:42:in `to_json'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/launchdarkly-server-sdk-5.8.0/lib/ldclient-rb/flags_state.rb:73:in `to_json'", "/home/vagrant/code/test-app/app/controllers/test_controller.rb:5:in `get'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:195:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:135:in `run_callbacks'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:41:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal/rescue.rb:22:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:136:in `process'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:39:in `process'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:190:in `dispatch'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:254:in `dispatch'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:567:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:101:in `run_callbacks'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/web-console-4.0.4/lib/web_console/middleware.rb:132:in `call_app'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/web-console-4.0.4/lib/web_console/middleware.rb:28:in `block in call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/web-console-4.0.4/lib/web_console/middleware.rb:17:in `catch'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/web-console-4.0.4/lib/web_console/middleware.rb:17:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:37:in `call_app'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `block in call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/activesupport-6.0.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/static.rb:126:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/webpacker-4.3.0/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/puma-4.3.6/lib/puma/configuration.rb:228:in `call'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/puma-4.3.6/lib/puma/server.rb:713:in `handle_request'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/puma-4.3.6/lib/puma/server.rb:472:in `process_client'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/puma-4.3.6/lib/puma/server.rb:328:in `block in run'", "/home/vagrant/.rvm/gems/ruby-2.5.6/gems/puma-4.3.6/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"]


`.as_json.to_json` still works.

**Comment by eli-darkly** [comment]
Well, `key: 1` is not recommended - the user key is supposed to be a string, and although I think the SDK is supposed to transparently convert it to a string, I'd be curious to know if you get different results with `key: "1"`. The error message there is a bit odd though in any case; I can't think why it would be getting a symbol value in any place where it didn't expect one.

It's helpful to know that this is specifically in Rails. It looks like it's using the ActiveSupport implementation of JSON encoding rather than the standard `json` gem— I'm not sure exactly how that happens or how the behavior might be different, but that at least gives me an area to look into further.

**Comment by binan-trc** [comment]
Switching to `key: "1"` does give the same error but it is good to know integer is not recommended I will try to use string keys in the future.
